tools:
- name: fastqc
  owner: devteam
  revisions:
  - ff9530579d1f
  tool_panel_section_label: QC
  tool_shed_url: toolshed.g2.bx.psu.edu

- name: trimmomatic
  owner: pjbriggs
  revisions:
  - 53af7b5b1b56
  tool_panel_section_label: QC
  tool_shed_url: toolshed.g2.bx.psu.edu

- name: qualimap_suite
  owner: joachim-jacob
  revisions:
  - f6ffb9aa409e
  tool_panel_section_label: QC
  tool_shed_url: toolshed.g2.bx.psu.edu

- name: bismark
  owner: bgruening
  revisions:
  - fcadce4d9a06
  tool_panel_section_label: Mappers
  tool_shed_url: toolshed.g2.bx.psu.edu

- name: htseq_count
  owner: lparsons
  revisions:
  - 620d5603d1a8
  tool_panel_section_label: RNA-Seq
  tool_shed_url: toolshed.g2.bx.psu.edu

- name: meme_meme
  owner: iuc
  revisions:
  - b8c05adb68da
  tool_panel_section_label: Motif
  tool_shed_url: toolshed.g2.bx.psu.edu

- name: meme_fimo
  owner: iuc
  revisions:
  - c470b36b592d
  tool_panel_section_label: Motif
  tool_shed_url: toolshed.g2.bx.psu.edu




- name: samtools_reheader
  owner: devteam
  revisions:
  - db000c6007a0
  tool_panel_section_label: SAM
  tool_shed_url: toolshed.g2.bx.psu.edu

- name: samtools_slice_bam
  owner: devteam
  revisions:
  - a4a10c7924d1
  tool_panel_section_label: SAM
  tool_shed_url: toolshed.g2.bx.psu.edu

- name: samtools_flagstat
  owner: devteam
  revisions:
  - cc61ade70eb8
  tool_panel_section_label: SAM
  tool_shed_url: toolshed.g2.bx.psu.edu

- name: bam_to_sam
  owner: devteam
  revisions:
  - f57df915aa10
  tool_panel_section_label: SAM
  tool_shed_url: toolshed.g2.bx.psu.edu

- name: samtools_split
  owner: devteam
  revisions:
  - b7f7826ef1cd
  tool_panel_section_label: SAM
  tool_shed_url: toolshed.g2.bx.psu.edu

- name: samtools_stats
  owner: devteam
  revisions:
  - 24c5d43cb545
  tool_panel_section_label: SAM
  tool_shed_url: toolshed.g2.bx.psu.edu

- name: samtools_calmd
  owner: devteam
  revisions:
  - 33208952b99d
  tool_panel_section_label: SAM
  tool_shed_url: toolshed.g2.bx.psu.edu

- name: samtools_mpileup
  owner: devteam
  revisions:
  - 583abf29fc8e
  tool_panel_section_label: SAM
  tool_shed_url: toolshed.g2.bx.psu.edu

- name: sam_to_bam
  owner: devteam
  revisions:
  - f7a0d41036c7
  tool_panel_section_label: SAM
  tool_shed_url: toolshed.g2.bx.psu.edu

- name: samtools_rmdup
  owner: devteam
  revisions:
  - 9129584416e2
  tool_panel_section_label: SAM
  tool_shed_url: toolshed.g2.bx.psu.edu

- name: samtools_bedcov
  owner: devteam
  revisions:
  - 12749212f61b
  tool_panel_section_label: SAM
  tool_shed_url: toolshed.g2.bx.psu.edu

- name: samtools_idxstats
  owner: devteam
  revisions:
  - 88b8c2916784
  tool_panel_section_label: SAM
  tool_shed_url: toolshed.g2.bx.psu.edu

- name: samtools_sort
  owner: devteam
  revisions:
  - cab3f8d35989
  tool_panel_section_label: SAM
  tool_shed_url: toolshed.g2.bx.psu.edu



- name: deeptools_bam_compare
  owner: bgruening
  revisions:
  - a1ca9bccc7f2
  tool_panel_section_label: deepTools
  tool_shed_url: toolshed.g2.bx.psu.edu

- name: deeptools_bam_coverage
  owner: bgruening
  revisions:
  - 5d11599b8a7d
  tool_panel_section_label: deepTools
  tool_shed_url: toolshed.g2.bx.psu.edu

- name: deeptools_plot_correlation
  owner: bgruening
  revisions:
  - f264afa9fa6f
  tool_panel_section_label: deepTools
  tool_shed_url: toolshed.g2.bx.psu.edu

- name: deeptools_bam_pe_fragmentsize
  owner: bgruening
  revisions:
  - 81b1e3e1fc6c
  tool_panel_section_label: deepTools
  tool_shed_url: toolshed.g2.bx.psu.edu

- name: deeptools_compute_matrix_operations
  owner: bgruening
  revisions:
  - 72bfafe3330b
  tool_panel_section_label: deepTools
  tool_shed_url: toolshed.g2.bx.psu.edu

- name: deeptools_compute_matrix
  owner: bgruening
  revisions:
  - fd1275e01605
  tool_panel_section_label: deepTools
  tool_shed_url: toolshed.g2.bx.psu.edu

- name: deeptools_plot_fingerprint
  owner: bgruening
  revisions:
  - f8fc4e5aff9d
  tool_panel_section_label: deepTools
  tool_shed_url: toolshed.g2.bx.psu.edu

- name: deeptools_multi_bam_summary
  owner: bgruening
  revisions:
  - 2d466b530754
  tool_panel_section_label: deepTools
  tool_shed_url: toolshed.g2.bx.psu.edu

- name: deeptools_plot_heatmap
  owner: bgruening
  revisions:
  - 512155688d98
  tool_panel_section_label: deepTools
  tool_shed_url: toolshed.g2.bx.psu.edu

- name: deeptools_plot_enrichment
  owner: bgruening
  revisions:
  - 94ca68515826
  tool_panel_section_label: deepTools
  tool_shed_url: toolshed.g2.bx.psu.edu

- name: deeptools_compute_gc_bias
  owner: bgruening
  revisions:
  - 29fcfd36e90a
  tool_panel_section_label: deepTools
  tool_shed_url: toolshed.g2.bx.psu.edu

- name: deeptools_bigwig_compare
  owner: bgruening
  revisions:
  - bfff7454b59a
  tool_panel_section_label: deepTools
  tool_shed_url: toolshed.g2.bx.psu.edu

- name: deeptools_multi_bigwig_summary
  owner: bgruening
  revisions:
  - db940c262830
  tool_panel_section_label: deepTools
  tool_shed_url: toolshed.g2.bx.psu.edu

- name: deeptools_plot_profile
  owner: bgruening
  revisions:
  - aac8444d6681
  tool_panel_section_label: deepTools
  tool_shed_url: toolshed.g2.bx.psu.edu

- name: deeptools_plot_pca
  owner: bgruening
  revisions:
  - 38e3f226248b
  tool_panel_section_label: deepTools
  tool_shed_url: toolshed.g2.bx.psu.edu

- name: deeptools_correct_gc_bias
  owner: bgruening
  revisions:
  - a02cfa31e9cb
  tool_panel_section_label: deepTools
  tool_shed_url: toolshed.g2.bx.psu.edu

- name: deeptools_plot_coverage
  owner: bgruening
  revisions:
  - 7e361d147872
  tool_panel_section_label: deepTools
  tool_shed_url: toolshed.g2.bx.psu.edu

- name: bedtools
  owner: iuc
  revisions:
  - bd7721ad15aa
  tool_panel_section_label: BED
  tool_shed_url: toolshed.g2.bx.psu.edu

- name: manorm
  owner: haydensun
  revisions:
  - 52225f471c57
  tool_panel_section_label: ChIP-Seq
  tool_shed_url: toolshed.g2.bx.psu.edu

- name: sicer
  owner: devteam
  revisions:
  - 4a14714649b4
  tool_panel_section_label: ChIP-Seq
  tool_shed_url: toolshed.g2.bx.psu.edu

- name: macs21
  owner: pjbriggs
  revisions:
  - 00d73c812399
  tool_panel_section_label: ChIP-Seq
  tool_shed_url: toolshed.g2.bx.psu.edu
